{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import datetime\n",
    "import gc\n",
    "import lightgbm as lgb\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import os\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import time\n",
    "import warnings\n",
    "\n",
    "from contextlib import contextmanager\n",
    "from pandas.core.common import SettingWithCopyWarning\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from sklearn.model_selection import KFold, StratifiedKFold\n",
    "\n",
    "warnings.simplefilter(action='ignore', category=SettingWithCopyWarning)\n",
    "warnings.simplefilter(action='ignore', category=FutureWarning)\n",
    "\n",
    "\n",
    "FEATS_EXCLUDED = [\n",
    "    'first_active_month', 'target', 'card_id', 'outliers',\n",
    "    'hist_purchase_date_max', 'hist_purchase_date_min', 'hist_card_id_size',\n",
    "    'new_purchase_date_max', 'new_purchase_date_min', 'new_card_id_size',\n",
    "    'OOF_PRED', 'month_0',\n",
    "    'new_month_lag_min','quarter','new_month_lag_max','hist_month_lag_max','new_month_diff_var'#40\n",
    "    'hist_hour_nunique','new_installments_sum','hist_installments_max','new_subsector_id_nunique',\n",
    "    'new_installments_max','hist_month_lag_min','new_weekofyear_nunique','new_weekend_mean','new_hour_nunique'#30\n",
    "    'hist_subsector_id_nunique']\n",
    "@contextmanager\n",
    "def timer(title):\n",
    "    t0 = time.time()\n",
    "    yield\n",
    "    print(\"{} - done in {:.0f}s\".format(title, time.time() - t0))\n",
    "\n",
    "# rmse\n",
    "def rmse(y_true, y_pred):\n",
    "    return np.sqrt(mean_squared_error(y_true, y_pred))\n",
    "\n",
    "# One-hot encoding for categorical columns with get_dummies\n",
    "def one_hot_encoder(df, nan_as_category = True):\n",
    "    original_columns = list(df.columns)\n",
    "    categorical_columns = [col for col in df.columns if df[col].dtype == 'object']\n",
    "    df = pd.get_dummies(df, columns= categorical_columns, dummy_na= nan_as_category)\n",
    "    new_columns = [c for c in df.columns if c not in original_columns]\n",
    "    return df, new_columns\n",
    "    \n",
    "# Display/plot feature importance\n",
    "def display_importances(feature_importance_df_):\n",
    "    cols = feature_importance_df_[[\"feature\", \"importance\"]].groupby(\"feature\").mean().sort_values(by=\"importance\", ascending=False)[:40].index\n",
    "    best_features = feature_importance_df_.loc[feature_importance_df_.feature.isin(cols)]\n",
    "\n",
    "    plt.figure(figsize=(8, 10))\n",
    "    sns.barplot(x=\"importance\", y=\"feature\", data=best_features.sort_values(by=\"importance\", ascending=False))\n",
    "    plt.title('LightGBM Features (avg over folds)')\n",
    "    plt.tight_layout()\n",
    "    plt.savefig('lgbm_importances.png')\n",
    "\n",
    "# reduce memory\n",
    "def reduce_mem_usage(df, verbose=True):\n",
    "    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']\n",
    "    start_mem = df.memory_usage().sum() / 1024**2\n",
    "    for col in df.columns:\n",
    "        col_type = df[col].dtypes\n",
    "        if col_type in numerics:\n",
    "            c_min = df[col].min()\n",
    "            c_max = df[col].max()\n",
    "            if str(col_type)[:3] == 'int':\n",
    "                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:\n",
    "                    df[col] = df[col].astype(np.int8)\n",
    "                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:\n",
    "                    df[col] = df[col].astype(np.int16)\n",
    "                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:\n",
    "                    df[col] = df[col].astype(np.int32)\n",
    "                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:\n",
    "                    df[col] = df[col].astype(np.int64)\n",
    "            else:\n",
    "                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:\n",
    "                    df[col] = df[col].astype(np.float16)\n",
    "                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:\n",
    "                    df[col] = df[col].astype(np.float32)\n",
    "                else:\n",
    "                    df[col] = df[col].astype(np.float64)\n",
    "\n",
    "    end_mem = df.memory_usage().sum() / 1024**2\n",
    "    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))\n",
    "    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))\n",
    "\n",
    "    return df\n",
    "    \n",
    "\n",
    "\n",
    "# LightGBM GBDT with KFold or Stratified KFold\n",
    "def kfold_lightgbm(train_df, test_df, num_folds, stratified = False, debug= False):\n",
    "    print(\"Starting LightGBM. Train shape: {}, test shape: {}\".format(train_df.shape, test_df.shape))\n",
    "\n",
    "    # Cross validation model\n",
    "    if stratified:\n",
    "        folds = StratifiedKFold(n_splits= num_folds, shuffle=True, random_state=326)\n",
    "    else:\n",
    "        folds = KFold(n_splits= num_folds, shuffle=True, random_state=326)\n",
    "\n",
    "    # Create arrays and dataframes to store results\n",
    "    oof_preds = np.zeros(train_df.shape[0])\n",
    "    sub_preds = np.zeros(test_df.shape[0])\n",
    "    feature_importance_df = pd.DataFrame()\n",
    "    feats = [f for f in train_df.columns if f not in FEATS_EXCLUDED]\n",
    "\n",
    "    # k-fold\n",
    "    for n_fold, (train_idx, valid_idx) in enumerate(folds.split(train_df[feats], train_df['outliers'])):\n",
    "        train_x, train_y = train_df[feats].iloc[train_idx], train_df['target'].iloc[train_idx]\n",
    "        valid_x, valid_y = train_df[feats].iloc[valid_idx], train_df['target'].iloc[valid_idx]\n",
    "\n",
    "        # set data structure\n",
    "        lgb_train = lgb.Dataset(train_x,\n",
    "                                label=train_y,\n",
    "                                free_raw_data=False)\n",
    "        lgb_test = lgb.Dataset(valid_x,\n",
    "                               label=valid_y,\n",
    "                               free_raw_data=False)\n",
    "\n",
    "        # params optimized by optuna\n",
    "        params ={\n",
    "                'task': 'train',\n",
    "                'boosting': 'goss',\n",
    "                'objective': 'regression',\n",
    "                'metric': 'rmse',\n",
    "                'learning_rate': 0.01,\n",
    "                'subsample': 0.9855232997390695,\n",
    "                'max_depth': 7,\n",
    "                'top_rate': 0.9064148448434349,\n",
    "                'num_leaves': 63,\n",
    "                'min_child_weight': 41.9612869171337,\n",
    "                'other_rate': 0.0721768246018207,\n",
    "                'reg_alpha': 9.677537745007898,\n",
    "                'colsample_bytree': 0.5665320670155495,\n",
    "                'min_split_gain': 9.820197773625843,\n",
    "                'reg_lambda': 8.2532317400459,\n",
    "                'min_data_in_leaf': 21,\n",
    "                'verbose': -1,\n",
    "                'seed':int(2**n_fold),\n",
    "                'bagging_seed':int(2**n_fold),\n",
    "                'drop_seed':int(2**n_fold)\n",
    "                }\n",
    "\n",
    "        reg = lgb.train(\n",
    "                        params,\n",
    "                        lgb_train,\n",
    "                        valid_sets=[lgb_train, lgb_test],\n",
    "                        valid_names=['train', 'test'],\n",
    "                        num_boost_round=10000,\n",
    "                        early_stopping_rounds= 200,\n",
    "                        verbose_eval=100\n",
    "                        )\n",
    "\n",
    "        oof_preds[valid_idx] = reg.predict(valid_x, num_iteration=reg.best_iteration)\n",
    "        sub_preds += reg.predict(test_df[feats], num_iteration=reg.best_iteration) / folds.n_splits\n",
    "\n",
    "        fold_importance_df = pd.DataFrame()\n",
    "        fold_importance_df[\"feature\"] = feats\n",
    "        fold_importance_df[\"importance\"] = np.log1p(reg.feature_importance(importance_type='gain', iteration=reg.best_iteration))\n",
    "        fold_importance_df[\"fold\"] = n_fold + 1\n",
    "        feature_importance_df = pd.concat([feature_importance_df, fold_importance_df], axis=0)\n",
    "        print('Fold %2d RMSE : %.6f' % (n_fold + 1, rmse(valid_y, oof_preds[valid_idx])))\n",
    "        del reg, train_x, train_y, valid_x, valid_y\n",
    "        gc.collect()\n",
    "\n",
    "    # display importances\n",
    "    display_importances(feature_importance_df)\n",
    "\n",
    "    if not debug:\n",
    "        # save submission file\n",
    "        test_df.loc[:,'target'] = sub_preds\n",
    "        test_df = test_df.reset_index()\n",
    "        test_df[['card_id', 'target']].to_csv(submission_file_name, index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import lightgbm as lgb\n",
    "import numpy as np\n",
    "import sklearn.datasets\n",
    "import sklearn.metrics\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "import optuna\n",
    "\n",
    "def rmse(y_true, y_pred):\n",
    "    return np.sqrt(mean_squared_error(y_true, y_pred))\n",
    "\n",
    "def objective(trial):\n",
    "    \n",
    "    \n",
    "        num_folds = 11\n",
    "        train_x, train_y = train_df[feats], train_df['target']\n",
    "        #data, target = sklearn.datasets.load_breast_cancer(return_X_y=True)\n",
    "        '''dtrain = lgb.Dataset(train_x, label=train_y)'''\n",
    "       \n",
    "        lgbm_train = lgb.Dataset(train_x,\n",
    "                                 train_y,\n",
    "                                  free_raw_data=False\n",
    "                                  )\n",
    "\n",
    "        params = {'objective': 'regression',\n",
    "                  'metric': 'rmse',\n",
    "                  'verbosity': -1,\n",
    "                  \"learning_rate\": trial.suggest_uniform('learning_rate', 0.001, 1),\n",
    "                  \n",
    "                  'device': 'gpu',\n",
    "                  'gpu_platform_id': 1,\n",
    "                  'gpu_device_id': 0,\n",
    "                  'num_thread' : 1,\n",
    "                  'sparse_threshold' : 1,\n",
    "                  \n",
    "                  'seed': 2779,\n",
    "                  #'boosting_type': trial.suggest_categorical('boosting', ['gbdt',  'goss']),\n",
    "                  'num_leaves': trial.suggest_int('num_leaves', 16, 200),\n",
    "                  #'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.001, 1),\n",
    "                  'subsample': trial.suggest_uniform('subsample', 0.001, 1),\n",
    "                  'max_depth': trial.suggest_int('max_depth', 5, 20),\n",
    "                  'reg_alpha': trial.suggest_uniform('reg_alpha', 0, 10),\n",
    "                  # 'reg_lambda': trial.suggest_uniform('reg_lambda', 0, 10),\n",
    "                  #'min_split_gain': trial.suggest_uniform('min_split_gain', 0, 10),\n",
    "                  #'min_child_weight': trial.suggest_uniform('min_child_weight', 0, 45),\n",
    "                  #'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 16, 64)\n",
    "                  \n",
    "                  'min_child_samples' : trial.suggest_int('min_child_samples', 1, 200),\n",
    "                  #'num_iterations': trial.suggest_uniform('num_iterations', 1, 5000),\n",
    "                  'feature_fraction' : trial.suggest_uniform('feature_fraction', 0.001, 1),\n",
    "                  #'random_state': trial.suggest_int('random_state', 1, 5000),\n",
    "                  #'max_bin' :  trial.suggest_int('random_state', 1, 256)\n",
    "                  }\n",
    "\n",
    "        '''if params['boosting_type'] == 'dart':\n",
    "            params['drop_rate'] = trial.suggest_loguniform('drop_rate', 1e-8, 1.0)\n",
    "            params['skip_drop'] = trial.suggest_loguniform('skip_drop', 1e-8, 1.0)\n",
    "        if params['boosting_type'] == 'goss':\n",
    "            params['top_rate'] = trial.suggest_uniform('top_rate', 0.0, 1.0)\n",
    "            params['other_rate'] = trial.suggest_uniform('other_rate', 0.0, 1.0 - params['top_rate'])'''\n",
    "\n",
    "        #folds = StratifiedKFold(n_splits=NUM_FOLDS, shuffle=True, random_state=47)\n",
    "        folds = StratifiedKFold(n_splits= num_folds, shuffle=True, random_state=47)\n",
    "\n",
    "\n",
    "        clf = lgb.cv(\n",
    "                        params,\n",
    "                        lgbm_train,\n",
    "                        metrics=['rmse'],\n",
    "                        nfold=num_folds,\n",
    "                        folds=folds.split(train_df[feats], train_df['outliers']),\n",
    "                        num_boost_round=10000,\n",
    "                        early_stopping_rounds= 200,\n",
    "                        verbose_eval=100,\n",
    "                        seed=47\n",
    "            \n",
    "                         )\n",
    "        gc.collect()\n",
    "        return clf['rmse-mean'][-1]\n",
    "\n",
    "        \n",
    "        '''gbm = lgb.train(params, dtrain)\n",
    "        preds = gbm.predict(train_x)\n",
    "        pred_labels = np.rint(preds)\n",
    "        error =  rmse(train_y,preds)\n",
    "        #accuracy = sklearn.metrics.accuracy_score(test_y, pred_labels)\n",
    "        return error'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Memory usage after optimization is: 26.38 MB\n",
      "Decreased by 74.1%\n",
      "Memory usage after optimization is: 23.70 MB\n",
      "Decreased by 74.7%\n",
      "[100]\tcv_agg's rmse: 3.82791 + 0.0232763\n",
      "[200]\tcv_agg's rmse: 3.8826 + 0.0248887\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:26:10,993] Finished a trial resulted in value: 3.7134986150705673. Current best value is 3.7134986150705673 with parameters: {'learning_rate': 0.37018241335392194, 'num_leaves': 102, 'subsample': 0.8615201645052978, 'max_depth': 14, 'reg_alpha': 8.339943652931943, 'min_child_samples': 22, 'feature_fraction': 0.37343060042557186}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 4.24597 + 0.0352717\n",
      "[200]\tcv_agg's rmse: 4.41099 + 0.0319728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:29:47,894] Finished a trial resulted in value: 3.7082614899740545. Current best value is 3.7082614899740545 with parameters: {'learning_rate': 0.8366374994969353, 'num_leaves': 161, 'subsample': 0.0120844015099608, 'max_depth': 18, 'reg_alpha': 3.491205675249871, 'min_child_samples': 169, 'feature_fraction': 0.3849077264659108}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.748 + 0.0357499\n",
      "[200]\tcv_agg's rmse: 3.79479 + 0.03663\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:31:56,884] Finished a trial resulted in value: 3.6900568975265973. Current best value is 3.6900568975265973 with parameters: {'learning_rate': 0.30788531034276967, 'num_leaves': 73, 'subsample': 0.7990863898974492, 'max_depth': 16, 'reg_alpha': 2.5589512735536, 'min_child_samples': 61, 'feature_fraction': 0.4608027709115782}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.76276 + 0.0253263\n",
      "[200]\tcv_agg's rmse: 3.82333 + 0.0256985\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:33:44,264] Finished a trial resulted in value: 3.6844044755077046. Current best value is 3.6844044755077046 with parameters: {'learning_rate': 0.4316104657506093, 'num_leaves': 48, 'subsample': 0.0014843446657502857, 'max_depth': 16, 'reg_alpha': 2.2143718324698725, 'min_child_samples': 182, 'feature_fraction': 0.7233410359117122}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.94613 + 0.0263586\n",
      "[200]\tcv_agg's rmse: 4.06504 + 0.0271014\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:37:03,325] Finished a trial resulted in value: 3.691816345892215. Current best value is 3.6844044755077046 with parameters: {'learning_rate': 0.4316104657506093, 'num_leaves': 48, 'subsample': 0.0014843446657502857, 'max_depth': 16, 'reg_alpha': 2.2143718324698725, 'min_child_samples': 182, 'feature_fraction': 0.7233410359117122}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.7219 + 0.0257955\n",
      "[200]\tcv_agg's rmse: 3.7518 + 0.0298624\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:39:55,331] Finished a trial resulted in value: 3.7022051655300743. Current best value is 3.6844044755077046 with parameters: {'learning_rate': 0.4316104657506093, 'num_leaves': 48, 'subsample': 0.0014843446657502857, 'max_depth': 16, 'reg_alpha': 2.2143718324698725, 'min_child_samples': 182, 'feature_fraction': 0.7233410359117122}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 4.15425 + 0.0224362\n",
      "[200]\tcv_agg's rmse: 4.326 + 0.0288318\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:41:21,389] Finished a trial resulted in value: 3.7098580553275338. Current best value is 3.6844044755077046 with parameters: {'learning_rate': 0.4316104657506093, 'num_leaves': 48, 'subsample': 0.0014843446657502857, 'max_depth': 16, 'reg_alpha': 2.2143718324698725, 'min_child_samples': 182, 'feature_fraction': 0.7233410359117122}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.65767 + 0.0274673\n",
      "[200]\tcv_agg's rmse: 3.66716 + 0.0292932\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:43:20,168] Finished a trial resulted in value: 3.6539518322613542. Current best value is 3.6539518322613542 with parameters: {'learning_rate': 0.11610799508878916, 'num_leaves': 77, 'subsample': 0.46259974714863705, 'max_depth': 8, 'reg_alpha': 7.6055284337946985, 'min_child_samples': 85, 'feature_fraction': 0.9238425852119821}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.66915 + 0.0284634\n",
      "[200]\tcv_agg's rmse: 3.68262 + 0.028492\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:49:06,177] Finished a trial resulted in value: 3.661319029191374. Current best value is 3.6539518322613542 with parameters: {'learning_rate': 0.11610799508878916, 'num_leaves': 77, 'subsample': 0.46259974714863705, 'max_depth': 8, 'reg_alpha': 7.6055284337946985, 'min_child_samples': 85, 'feature_fraction': 0.9238425852119821}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.65732 + 0.0292061\n",
      "[200]\tcv_agg's rmse: 3.66148 + 0.0305027\n",
      "[300]\tcv_agg's rmse: 3.66792 + 0.0313588\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 11:56:25,039] Finished a trial resulted in value: 3.657000632106927. Current best value is 3.6539518322613542 with parameters: {'learning_rate': 0.11610799508878916, 'num_leaves': 77, 'subsample': 0.46259974714863705, 'max_depth': 8, 'reg_alpha': 7.6055284337946985, 'min_child_samples': 85, 'feature_fraction': 0.9238425852119821}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.79192 + 0.00883143\n",
      "[200]\tcv_agg's rmse: 3.76997 + 0.0101575\n",
      "[300]\tcv_agg's rmse: 3.76161 + 0.0108172\n",
      "[400]\tcv_agg's rmse: 3.75575 + 0.011553\n",
      "[500]\tcv_agg's rmse: 3.75246 + 0.0119368\n",
      "[600]\tcv_agg's rmse: 3.75014 + 0.0122304\n",
      "[700]\tcv_agg's rmse: 3.74894 + 0.0125259\n",
      "[800]\tcv_agg's rmse: 3.74735 + 0.0128124\n",
      "[900]\tcv_agg's rmse: 3.74677 + 0.0130484\n",
      "[1000]\tcv_agg's rmse: 3.7458 + 0.0131291\n",
      "[1100]\tcv_agg's rmse: 3.74522 + 0.0132302\n",
      "[1200]\tcv_agg's rmse: 3.74471 + 0.0133304\n",
      "[1300]\tcv_agg's rmse: 3.74442 + 0.0134502\n",
      "[1400]\tcv_agg's rmse: 3.7443 + 0.013496\n",
      "[1500]\tcv_agg's rmse: 3.74409 + 0.0136722\n",
      "[1600]\tcv_agg's rmse: 3.74359 + 0.0137418\n",
      "[1700]\tcv_agg's rmse: 3.74344 + 0.0138286\n",
      "[1800]\tcv_agg's rmse: 3.74345 + 0.0138851\n",
      "[1900]\tcv_agg's rmse: 3.74334 + 0.0139596\n",
      "[2000]\tcv_agg's rmse: 3.74347 + 0.0139793\n",
      "[2100]\tcv_agg's rmse: 3.7434 + 0.0140429\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 12:11:35,618] Finished a trial resulted in value: 3.743344263784014. Current best value is 3.6539518322613542 with parameters: {'learning_rate': 0.11610799508878916, 'num_leaves': 77, 'subsample': 0.46259974714863705, 'max_depth': 8, 'reg_alpha': 7.6055284337946985, 'min_child_samples': 85, 'feature_fraction': 0.9238425852119821}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.75896 + 0.0320274\n",
      "[200]\tcv_agg's rmse: 3.81554 + 0.0332836\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 12:13:30,965] Finished a trial resulted in value: 3.6898789106766396. Current best value is 3.6539518322613542 with parameters: {'learning_rate': 0.11610799508878916, 'num_leaves': 77, 'subsample': 0.46259974714863705, 'max_depth': 8, 'reg_alpha': 7.6055284337946985, 'min_child_samples': 85, 'feature_fraction': 0.9238425852119821}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.67404 + 0.0297703\n",
      "[200]\tcv_agg's rmse: 3.68954 + 0.0294674\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2019-02-25 12:18:09,548] Finished a trial resulted in value: 3.6686608420648525. Current best value is 3.6539518322613542 with parameters: {'learning_rate': 0.11610799508878916, 'num_leaves': 77, 'subsample': 0.46259974714863705, 'max_depth': 8, 'reg_alpha': 7.6055284337946985, 'min_child_samples': 85, 'feature_fraction': 0.9238425852119821}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[100]\tcv_agg's rmse: 3.81064 + 0.00738081\n",
      "[200]\tcv_agg's rmse: 3.77983 + 0.00790261\n",
      "[300]\tcv_agg's rmse: 3.75601 + 0.00912017\n",
      "[400]\tcv_agg's rmse: 3.73755 + 0.0106157\n",
      "[500]\tcv_agg's rmse: 3.72338 + 0.0121134\n",
      "[600]\tcv_agg's rmse: 3.71217 + 0.0133994\n",
      "[700]\tcv_agg's rmse: 3.70324 + 0.0145915\n",
      "[800]\tcv_agg's rmse: 3.69597 + 0.0157218\n",
      "[900]\tcv_agg's rmse: 3.68998 + 0.0166475\n",
      "[1000]\tcv_agg's rmse: 3.68511 + 0.0175338\n",
      "[1100]\tcv_agg's rmse: 3.68096 + 0.0183115\n",
      "[1200]\tcv_agg's rmse: 3.67755 + 0.0189919\n",
      "[1300]\tcv_agg's rmse: 3.67471 + 0.0196507\n",
      "[1400]\tcv_agg's rmse: 3.67226 + 0.0203033\n",
      "[1500]\tcv_agg's rmse: 3.67007 + 0.0208607\n",
      "[1600]\tcv_agg's rmse: 3.66823 + 0.0214114\n",
      "[1700]\tcv_agg's rmse: 3.6666 + 0.0218881\n",
      "[1800]\tcv_agg's rmse: 3.66521 + 0.0223077\n",
      "[1900]\tcv_agg's rmse: 3.66401 + 0.0227228\n",
      "[2000]\tcv_agg's rmse: 3.66291 + 0.0230524\n",
      "[2100]\tcv_agg's rmse: 3.66187 + 0.0233727\n",
      "[2200]\tcv_agg's rmse: 3.66092 + 0.0236706\n",
      "[2300]\tcv_agg's rmse: 3.66004 + 0.0239392\n",
      "[2400]\tcv_agg's rmse: 3.65925 + 0.0241432\n",
      "[2500]\tcv_agg's rmse: 3.65851 + 0.0243505\n",
      "[2600]\tcv_agg's rmse: 3.65782 + 0.0245458\n",
      "[2700]\tcv_agg's rmse: 3.65719 + 0.0247721\n",
      "[2800]\tcv_agg's rmse: 3.6566 + 0.0249364\n",
      "[2900]\tcv_agg's rmse: 3.65605 + 0.0250537\n",
      "[3000]\tcv_agg's rmse: 3.65553 + 0.0251532\n",
      "[3100]\tcv_agg's rmse: 3.65502 + 0.025258\n",
      "[3200]\tcv_agg's rmse: 3.65456 + 0.0253669\n",
      "[3300]\tcv_agg's rmse: 3.6541 + 0.0254664\n",
      "[3400]\tcv_agg's rmse: 3.65367 + 0.0255854\n",
      "[3500]\tcv_agg's rmse: 3.65328 + 0.0256898\n",
      "[3600]\tcv_agg's rmse: 3.65292 + 0.0258184\n",
      "[3700]\tcv_agg's rmse: 3.65256 + 0.0259535\n",
      "[3800]\tcv_agg's rmse: 3.65218 + 0.0260907\n",
      "[3900]\tcv_agg's rmse: 3.65187 + 0.0262116\n",
      "[4000]\tcv_agg's rmse: 3.6516 + 0.0263404\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[W 2019-02-25 13:23:09,470] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 487, in cv\n",
      "    cvfolds.update(fobj=fobj)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 263, in handler_function\n",
      "    ret.append(getattr(booster, name)(*args, **kwargs))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1789, in update\n",
      "    ctypes.byref(is_finished)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "Exception ignored in: <bound method Booster.__del__ of <lightgbm.basic.Booster object at 0x0000000014FBA630>>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1590, in __del__\n",
      "    _safe_call(_LIB.LGBM_BoosterFree(self.handle))\n",
      "OSError: exception: access violation reading 0x0000000000000000\n",
      "Exception ignored in: <bound method Booster.__del__ of <lightgbm.basic.Booster object at 0x0000000014FBA358>>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1590, in __del__\n",
      "    _safe_call(_LIB.LGBM_BoosterFree(self.handle))\n",
      "OSError: exception: access violation reading 0x0000000000000000\n",
      "Exception ignored in: <bound method Booster.__del__ of <lightgbm.basic.Booster object at 0x0000000014FBA0B8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1590, in __del__\n",
      "    _safe_call(_LIB.LGBM_BoosterFree(self.handle))\n",
      "OSError: exception: access violation reading 0x0000000000000000\n",
      "Exception ignored in: <bound method Booster.__del__ of <lightgbm.basic.Booster object at 0x0000000014FC93C8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1590, in __del__\n",
      "    _safe_call(_LIB.LGBM_BoosterFree(self.handle))\n",
      "OSError: exception: access violation reading 0x0000000000000000\n",
      "[W 2019-02-25 13:23:11,458] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:13,011] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:14,543] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:16,068] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:17,589] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:19,112] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:20,648] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:22,173] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:23,687] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:25,214] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:26,733] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:28,253] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:29,782] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:31,310] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:32,942] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:34,592] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:36,179] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:37,720] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:39,257] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:40,788] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:42,325] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:43,861] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:45,404] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:46,932] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:48,460] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:49,995] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:51,522] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:53,043] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:54,579] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:56,143] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:57,669] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:23:59,207] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:00,740] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:02,272] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:03,803] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:05,337] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:06,870] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:08,405] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:09,949] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:11,490] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:13,028] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:14,571] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:16,102] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:17,634] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:19,164] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:20,720] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:22,276] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:23,823] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:25,369] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:26,921] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:28,456] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:30,000] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:31,553] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:33,099] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:34,648] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:36,190] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:37,725] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:39,261] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:40,811] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:42,351] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:43,889] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:45,437] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:46,987] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:48,524] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:50,077] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:51,672] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:53,216] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:54,763] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:56,307] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:57,842] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:24:59,392] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:00,943] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:02,502] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:04,049] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:05,600] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:07,144] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:08,688] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:10,238] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:11,781] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:13,322] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:14,881] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:16,426] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:17,970] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:19,521] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:21,067] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n",
      "[W 2019-02-25 13:25:22,611] Setting trial status as TrialState.FAIL because of the following error: LightGBMError('Out of Resources',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\optuna\\study.py\", line 409, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-4-63625ec2837d>\", line 75, in objective\n",
      "    seed=47\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 458, in cv\n",
      "    stratified=stratified, shuffle=shuffle)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\engine.py\", line 317, in _make_n_folds\n",
      "    cvbooster = Booster(tparam, train_set)\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 1541, in __init__\n",
      "    ctypes.byref(self.handle)))\n",
      "  File \"C:\\Anaconda3\\lib\\site-packages\\lightgbm\\basic.py\", line 46, in _safe_call\n",
      "    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))\n",
      "lightgbm.basic.LightGBMError: Out of Resources\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of finished trials: 100\n",
      "Best trial:\n",
      "  Value: 3.6539518322613542\n",
      "  Params: \n",
      "    learning_rate: 0.11610799508878916\n",
      "    num_leaves: 77\n",
      "    subsample: 0.46259974714863705\n",
      "    max_depth: 8\n",
      "    reg_alpha: 7.6055284337946985\n",
      "    min_child_samples: 85\n",
      "    feature_fraction: 0.9238425852119821\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-5-b8dba4ad12b0>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     23\u001b[0m         \u001b[0mhist_df\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mto_csv\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"optuna_result_lgbm.csv\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     24\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 25\u001b[1;33m         \u001b[1;32mdel\u001b[0m \u001b[0mdf\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     26\u001b[0m         \u001b[0mgc\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcollect\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'df' is not defined"
     ]
    }
   ],
   "source": [
    "with timer(\"split train & test\"):\n",
    "        train_df = reduce_mem_usage(pd.read_csv('low_features3.csv'))\n",
    "        test_df = reduce_mem_usage(pd.read_csv('test_clean3.csv'))\n",
    "       \n",
    "        feature_importance_df = pd.DataFrame()\n",
    "        feats = [f for f in train_df.columns if f not in FEATS_EXCLUDED]\n",
    "        \n",
    "        study = optuna.create_study()\n",
    "        study.optimize(objective, n_trials=100)\n",
    "\n",
    "        print('Number of finished trials: {}'.format(len(study.trials)))\n",
    "\n",
    "        print('Best trial:')\n",
    "        trial = study.best_trial\n",
    "\n",
    "        print('  Value: {}'.format(trial.value))\n",
    "\n",
    "        print('  Params: ')\n",
    "        for key, value in trial.params.items():\n",
    "            print('    {}: {}'.format(key, value))\n",
    "        \n",
    "        hist_df = study.trials_dataframe()\n",
    "        hist_df.to_csv(\"optuna_result_lgbm.csv\")\n",
    "\n",
    "        del df\n",
    "        gc.collect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
